# config.mk
#
# Product-specific compile-time definitions.
#
TARGET_BOARD_PLATFORM := exynos4
TARGET_SOC := exynos4x12

# CPU options
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_NO_BOOTLOADER := true
# mj
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true
TARGET_PROVIDES_INIT_TARGET_RC := true
TARGET_BOOTLOADER_BOARD_NAME := smdk4x12

BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_I2S_AUDIO := true
BOARD_USES_PCM_AUDIO := false
BOARD_USES_SPDIF_AUDIO := false
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_CSR := true

# ULP Audio
USE_ULP_AUDIO := true

# ALP Audio
BOARD_USE_ALP_AUDIO := false

# SEC Camera
USE_SEC_CAMERA := false
CAMERA_USE_DIGITALZOOM := true
BOARD_USE_S5K3H2:= false


# Enable JIT
WITH_JIT := true

BOARD_EMMC_BSP := false

BOARD_HAS_TWOSTORAGES := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 314572800
BOARD_USERDATAIMAGE_PARTITION_SIZE := 314572800
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_USES_HGL := true
BOARD_NO_32BPP := true

BOARD_USES_HDMI_SUBTITLES := false
BOARD_USES_HDMI := true
BOARD_HDMI_STD := STD_1080P
BOARD_HDMI_DDC_CH := DDC_CH_I2C_0
BOARD_USES_FIMGAPI := true

BOARD_USE_SAMSUNG_COLORFORMAT := true
BOARD_NONBLOCK_MODE_PROCESS := true
BOARD_USE_STOREMETADATA := true
BOARD_USE_METADATABUFFERTYPE := true
BOARD_USES_MFC_FPS := true
BOARD_USE_S3D_SUPPORT := true
BOARD_USE_CSC_FIMC := false

BOARD_USES_HIGH_RESOLUTION_LCD := true

BOARD_USES_FFMPEG := false

# Enable V4L2 & ION
BOARD_USE_V4L2 := false
BOARD_USE_V4L2_ION := false
BOARD_NO_OVERLAY := false

SCREEN_WIDTH := 1024
SCREEN_HEIGHT := 768
DEFAULT_FB_NUM := 0

USE_OPENGL_RENDERER := true

# For Olca3.2 driver
#BOARD_WPA_SUPPLICANT_DRIVER := NL80211
#BOARD_HOSTAPD_DRIVER := NL80211
#WPA_SUPPLICANT_VERSION := VER_0_8_ATHEROS
#HOSTAPD_VERSION := VER_0_8_ATHEROS
#WIFI_DRIVER_MODULE_PATH         := "/system/lib/modules/ath6kl_sdio.ko"
#WIFI_DRIVER_MODULE_NAME         := "ath6kl_sdio"

#WIFI_SDIO_IF_DRIVER_MODULE_PATH := "/system/lib/modules/cfg80211.ko"
#WIFI_SDIO_IF_DRIVER_MODULE_NAME := "cfg80211"
#WIFI_SDIO_IF_DRIVER_MODULE_ARG  := ""

BOARD_HAVE_MTK_MT6620 := true
BOARD_GPS_LIBRARIES := true
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/wlan.ko
WIFI_DRIVER_MODULE_NAME := wlan0
WPA_BUILD_SUPPLICANT := true
#CONFIG_CTRL_IFACE := y
WPA_SUPPLICANT_VERSION := VER_0_6_X
P2P_SUPPLICANT_VERSION := VER_0_8_X
BOARD_P2P_SUPPLICANT_DRIVER := NL80211

#add by cym 20130623
BOARD_HAVE_MPU6050 := false
#end add
#add by cym 20150305
BOARD_HAVE_GNS7560 := false
#end add
